import java.text.DateFormat
import java.text.SimpleDateFormat

apply plugin: 'com.android.application'

android {
    signingConfigs {
    }

    defaultConfig {
        applicationId "ru.arvalon.chucknorrisjokes"
        minSdkVersion 21
        compileSdk 36
        targetSdkVersion 36
        versionCode 14
        versionName "5.4"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

        String finalName = "ChuckNorrisJokes_v." + defaultConfig.versionName+"_"+getDateTime()
        setProperty("archivesBaseName", finalName);
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    namespace 'ru.arvalon.chucknorrisjokes'
}

def getDateTime() {
    DateFormat df = new SimpleDateFormat("MM.dd_HH.mm");

    return df.format(new Date());
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    testImplementation 'junit:junit:4.13.2'

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'

    implementation "com.github.moxy-community:moxy-androidx:2.2.2"
    annotationProcessor "com.github.moxy-community:moxy-compiler:2.2.2"

    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'

    implementation 'com.vk:androidsdk:1.6.7'
}
